name: Deploy to Minikube using GitHub Actions
on: 
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Load Code
        uses: actions/checkout@v2
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
      - name: Cluster liveness check
        run: kubectl get pods -A
      - name: Build docker image
        run: |
          eval $(minikube docker-env)
          docker build -t devopshint/node-app:latest .
          echo "Verifying images:"
          docker images
      - name: Apply manifest
        run: kubectl apply -f k8s-node-app.yaml
      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url